In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
pop=pd.read_csv('/content/drive/MyDrive/STATS/SP500_pop.csv',header=None,usecols=[1])
pop.head()

1
0  0.469930
1  0.114371
2 -0.410537
3  0.461147
4  0.544395

In [16]:
samp=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Stats/sample.csv',header=None,usecols=[1])
samp.head()

1
0  0.415768
1  0.159440
2  0.480122
3  0.575228
4 -0.034514

In [17]:
pop.size,samp.size

(500, 50)

In [18]:
np.isin(samp,pop)

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

# Measure of Central tendency-Mean, Median, Mode

In [20]:
pop.mean(),samp.mean()

(1    0.217803
 dtype: float64, 1    0.253186
 dtype: float64)

In [21]:
pop.median(),samp.median()

(1    0.181588
 dtype: float64, 1    0.190916
 dtype: float64)

In [24]:
pop.mode(numeric_only=True) #Output shows that no mode is available for this continous dataset

1
0   -0.513006
1   -0.503270
2   -0.470799
3   -0.447663
4   -0.410537
..        ...
495  1.227227
496  1.311349
497  1.323002
498  1.434432
499  3.867156

[500 rows x 1 columns]

# Geometric mean

In [25]:
#Consider an array that contains returns of 4 years between 2015 and 2018. Compute the geometric mean of years 2016

In [27]:
prices=np.array([100,107,102,110])
prices

array([100, 107, 102, 110])

In [28]:
110/100**(1/prices.size)

34.78505426185217

In [29]:
#Another method is compute returns year wise first and then apply the formula

In [31]:
returns=prices[1:]/prices[:-1]-1
returns

array([ 0.07      , -0.04672897,  0.07843137])

In [33]:
(returns+1).prod()**(1/prices.size)-1 #GM

0.02411368908444511

In [36]:
returns.mean() #AM  Note that AM is usually higher than GM

0.033900800195467595

# Percentile

In [37]:
pop.median() # Implies that 50% of values fall under hte value 0.18

1    0.181588
dtype: float64

In [39]:
np.percentile(pop,50) #Yields same as that of median, however can be customized for different value ranges

0.18158807954190953

In [40]:
np.percentile(pop,90) #90% of values fall below 0.52

0.5259665531267785

In [42]:
np.percentile(pop,[25,75]) #50% of values lie between 0.04 nd 0.35. However, the threhold % can be varied

array([0.04210105, 0.35553234])

# Measure of dispersion - Range, Variance, SD

In [44]:
pop.max()-pop.min(), samp.max()-samp.min() #RANGE

(1    4.380162
 dtype: float64, 1    1.450476
 dtype: float64)

In [48]:
pop.var(),samp.var(ddof=1) #if not divided by n-1, sample variable would get systematically under estimated

(1    0.096456
 dtype: float64, 1    0.093004
 dtype: float64)

In [51]:
np.sqrt(pop.var()),np.sqrt(samp.var(ddof=1)) #SD--> better in terms of interpretatbility when compared to variance

(1    0.310574
 dtype: float64, 1    0.304966
 dtype: float64)

#Higher order of moments - Skew, Kurtosis

In [52]:
import scipy.stats as stats

In [54]:
stats.skew(pop),stats.skew(samp)

(array([3.69215566]), array([1.25609294]))